version: "3"

# sudo systemctl start docker
# docker-compose up

services:
  react-app:
    build: 
      context: ./
      dockerfile: ./micro-minding-react_app/Dockerfile
      args:
        app_env: dev
    volumes:
      - ./micro-minding-react_app/src:/micro-minding-react_app/src
    ports:
      - 3000:3000

  grpc-gateway:
    build: 
      context: ./
      dockerfile: ./micro-minding-grpc_gateway/Dockerfile
      args:
        app_env: dev
    volumes:
      - ./micro-minding-grpc_gateway/app:/go/src/github.com/hannesrabo/micro-minding/micro-minding-grpc_gateway/app
    ports:
      - 8081:8081

  documents:
    build: 
      context: ./
      dockerfile: ./micro-minding-documents/Dockerfile
      args:
        app_env: dev
    volumes:
      - ./micro-minding-documents/app:/go/src/github.com/hannesrabo/micro-minding/micro-minding-documents/app
    ports:
      - 8082:8082

  user-auth:
    build: 
      context: ./
      dockerfile: ./micro-minding-user_aut/Dockerfile
      args:
        app_env: dev
    volumes:
      - ./micro-minding-user_aut/app:/go/src/github.com/hannesrabo/micro-minding/micro-minding-user_aut/app
    ports:
      - 8083:8083

